[project]
name = 'blockcity'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.blockcity]
path = 'contracts/blockcity.clar'
clarity_version = 2
epoch = 2.4

[contracts.constant-tradeables]
path = 'contracts/constant-tradables.clar'
clarity_version = 2
epoch = 2.4

[contracts.liquiditypool]
path = 'contracts/liquiditypool.clar'
clarity_version = 2
epoch = 2.4

[contracts.rewardscontract]
path = 'contracts/rewardscontract.clar'
clarity_version = 2
epoch = 2.4

[contracts.royalties]
path = 'contracts/royalties.clar'
clarity_version = 2
epoch = 2.4

[contracts.stx20]
path = 'contracts/stx20.clar'
clarity_version = 2
epoch = 2.4

[contracts.tradeables-trait]
path = 'contracts/tradables-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.tradeables-trait-ext]
path = 'contracts/tradables-trait-ext.clar'
clarity_version = 2
epoch = 2.4

[repl]
clarity_wasm_mode = false
show_timings = false

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
